version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: findly-backend-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "mysql://root:howpathetic1@db:3306/findly"
    env_file:
      - ./.env
    depends_on:
      - db
    volumes:
      - ./findly_uploads:/usr/src/app/findly-upload

  db:
    image: mysql:8.0
    container_name: findly-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: howpathetic1
      MYSQL_DATABASE: findly
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: findly-phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: "howpathetic1"  
    depends_on:
      - db

volumes:
  db_data: